version: '3.9'

services:  
     
  db:
    env_file: ./docker/.env-postgresql
    image: postgres:14
    volumes:
       - flaskdb:/var/lib/postgresql/data
       - pgconf:/etc/postgresql
       - pglog:/var/log/postgresql
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-irina@yandex.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123wert}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - backend

  flask_web:
    container_name: flask_web_container
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - 5000:5000
    restart: always
    depends_on: 
      - db
    networks:
      - backend

volumes:
    flaskdb:
      driver: local
    pgconf:
      driver: local
    pglog: 
      driver: local
    pgadmin:
      driver: local
    
networks:
  backend:
    driver: bridge